# Generated by Django 2.0 on 2020-02-23 12:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Epoch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('start_date', models.DateTimeField(default=datetime.datetime.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('color', models.CharField(blank=True, default='', max_length=64)),
                ('range', models.CharField(choices=[('SOP', 'Soprano'), ('ALT', 'Alto'), ('TEN', 'Tenor'), ('BAR', 'Baritone'), ('BAS', 'Bass')], default='TEN', max_length=3)),
                ('epoch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='music.Epoch')),
            ],
        ),
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('practising_hours', models.BigIntegerField(default=0)),
                ('alive', models.BooleanField(default=True)),
                ('bio', models.TextField()),
                ('instrument', models.ManyToManyField(to='music.Instrument')),
            ],
        ),
    ]
