# Generated by Django 2.0 on 2020-02-11 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Epoch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=128)),
                ('data', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='instrument',
            name='color',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instrument',
            name='name',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='instrument',
            name='strings',
            field=models.IntegerField(blank=True, default=1, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='instrument',
            name='epoch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='music.Epoch'),
        ),
    ]
