# Generated by Django 3.0.4 on 2020-03-24 18:46

from django.db import migrations, models


def update_alive(apps, schema_editor):
    Musician = apps.get_model('music', 'Musician')
    Musician.objects.update(
        alive=True
    )


def back(apps, schema_editor):
    ...


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20200324_1846'),
    ]

    operations = [
        migrations.RunPython(update_alive, back),
        migrations.AlterField(
            model_name='musician',
            name='alive',
            field=models.BooleanField(default=True),
        ),
    ]
