# Generated by Django 2.0 on 2020-02-17 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20200211_1946'),
    ]

    operations = [
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.RemoveField(
            model_name='instrument',
            name='strings',
        ),
        migrations.AddField(
            model_name='instrument',
            name='range',
            field=models.CharField(choices=[('SOP', 'Soprano'), ('ALT', 'Alto'), ('TEN', 'Tenor'), ('BAR', 'Baritone'), ('BAS', 'Bass')], default='TEN', max_length=3),
        ),
        migrations.AlterField(
            model_name='epoch',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='color',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AddField(
            model_name='musician',
            name='instrument',
            field=models.ManyToManyField(to='music.Instrument'),
        ),
    ]
