# Generated by Django 2.0 on 2020-02-18 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20200217_2143'),
    ]

    operations = [
        migrations.RenameField(
            model_name='epoch',
            old_name='data',
            new_name='date',
        ),
    ]
