# Generated by Django 3.0.3 on 2020-02-15 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_ad_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
